# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Existing version
        run: az version
        
      - name: uninstall existing cli
        run: start /wait msiexec -q -x {EACBF755-226E-46F6-8645-B080DC67883D}
        shell: cmd

      # Runs a set of commands using the runners shell
      - name: install new version
        run: |
          choco install azure-cli --version=2.33.0
          az version
